import type { Character, ScriptBlock, VnProject } from "./types.js";

function escapeRenpyString(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function charLookup(characters: Character[]): Map<string, Character> {
  const map = new Map<string, Character>();
  for (const c of characters) {
    map.set(c.id, c);
    map.set(c.defineName, c);
  }
  return map;
}

function emitBlock(
  block: ScriptBlock,
  chars: Map<string, Character>,
  indent = ""
): string[] {
  const lines: string[] = [];
  switch (block.type) {
    case "label":
      lines.push(`${indent}label ${block.name}:`);
      break;
    case "scene":
      lines.push(
        `${indent}scene ${block.image}${block.transition ? ` with ${block.transition}` : ""}`
      );
      break;
    case "show":
      lines.push(
        `${indent}show ${block.image}${block.at ? ` at ${block.at}` : ""}`
      );
      break;
    case "hide":
      lines.push(`${indent}hide ${block.image}`);
      break;
    case "narration":
      lines.push(`${indent}"${escapeRenpyString(block.text)}"`);
      break;
    case "dialogue": {
      const ch = chars.get(block.characterId);
      const who = ch?.defineName ?? "narrator";
      lines.push(`${indent}${who} "${escapeRenpyString(block.text)}"`);
      break;
    }
    case "menu": {
      lines.push(`${indent}menu${block.id ? ` ${block.id}` : ""}:`);
      if (block.prompt) {
        lines.push(`${indent}    "${escapeRenpyString(block.prompt)}"`);
      }
      for (const choice of block.choices) {
        lines.push(`${indent}    "${escapeRenpyString(choice.text)}":`);
        if (choice.jump) {
          lines.push(`${indent}        jump ${choice.jump}`);
        } else if (choice.blocks?.length) {
          for (const child of choice.blocks) {
            lines.push(...emitBlock(child, chars, indent + "        "));
          }
        } else {
          lines.push(`${indent}        pass`);
        }
      }
      break;
    }
    case "jump":
      lines.push(`${indent}jump ${block.target}`);
      break;
    case "return":
      lines.push(`${indent}return`);
      break;
    case "comment":
      lines.push(`${indent}# ${block.text}`);
      break;
    case "raw":
      for (const rawLine of block.code.split("\n")) {
        lines.push(`${indent}${rawLine}`);
      }
      break;
  }
  return lines;
}

/** Export character define lines for script.rpy header */
export function exportCharacterDefines(project: VnProject): string {
  const lines = ["# Characters — generated by VN Script Studio", ""];
  for (const c of project.characters) {
    const color = c.color ?? "#ffffff";
    lines.push(
      `define ${c.defineName} = Character("${escapeRenpyString(c.displayName)}", color="${color}")`
    );
  }
  return lines.join("\n") + "\n";
}

/** Export full project to a single .rpy string */
export function exportToRenpy(project: VnProject): string {
  const chars = charLookup(project.characters);
  const parts: string[] = [
    `# ${project.title}`,
    `# Generated by VN Script Studio`,
    project.logline ? `# Logline: ${project.logline}` : null,
    "",
    exportCharacterDefines(project).trimEnd(),
    "",
  ].filter((x): x is string => x !== null);

  for (const chapter of project.chapters) {
    parts.push(`# --- ${chapter.title} ---`);
    if (chapter.synopsis) parts.push(`# ${chapter.synopsis}`);
    let inLabel = false;
    for (const block of chapter.blocks) {
      if (block.type === "label") {
        inLabel = true;
        parts.push(...emitBlock(block, chars, ""));
      } else {
        parts.push(...emitBlock(block, chars, inLabel ? "    " : ""));
      }
    }
    parts.push("");
  }

  return parts.join("\n").replace(/\n{3,}/g, "\n\n");
}

/** Compact text dump for AI context (not full .rpy) */
export function projectToContext(project: VnProject, maxChars = 12000): string {
  const chars = project.characters
    .map(
      (c) =>
        `- ${c.displayName} (${c.defineName})${c.voice ? `: ${c.voice}` : ""}${c.bio ? ` | ${c.bio}` : ""}${c.relationships ? ` | 关系: ${c.relationships}` : ""}`
    )
    .join("\n");

  const bible = project.bible;
  let body = `# Project: ${project.title}\n`;
  if (project.logline) body += `Logline: ${project.logline}\n`;
  if (project.genre) body += `Genre: ${project.genre}\n`;
  if (bible?.world || project.lore) {
    body += `\n世界观:\n${bible?.world || project.lore}\n`;
  }
  if (bible?.background) body += `\n故事背景:\n${bible.background}\n`;
  if (bible?.outline) body += `\n大纲:\n${bible.outline}\n`;
  if (bible?.themes) body += `\n主题/基调:\n${bible.themes}\n`;
  if (bible?.notes) body += `\n备忘:\n${bible.notes}\n`;

  body += `\nCharacters:\n${chars || "(无)"}\n`;

  const locs = project.locations ?? [];
  if (locs.length) {
    body += `\nLocations:\n`;
    for (const l of locs) {
      body += `- ${l.name}${l.imageTag ? ` [${l.imageTag}]` : ""}${l.description ? `: ${l.description}` : ""}\n`;
    }
  }
  const links = project.locationLinks ?? [];
  if (links.length) {
    const byId = new Map(locs.map((l) => [l.id, l.name]));
    body += `Location links:\n`;
    for (const link of links) {
      body += `- ${byId.get(link.fromId) ?? link.fromId} --${link.relation}--> ${byId.get(link.toId) ?? link.toId}${link.note ? ` (${link.note})` : ""}\n`;
    }
  }

  const vars = project.variables ?? [];
  if (vars.length) {
    body += `\nVariables / 状态机:\n`;
    for (const v of vars) {
      body += `- ${v.name} (${v.key}: ${v.type}) = ${JSON.stringify(v.value)}${v.bindCharacterId ? ` [char:${v.bindCharacterId}]` : ""}${v.note ? ` // ${v.note}` : ""}\n`;
    }
  }
  const sprites = project.sprites ?? [];
  if (sprites.length) {
    body += `\nSprites / 立绘:\n`;
    for (const s of sprites) {
      const ex = s.expressions.map((e) => e.tag).join(", ");
      body += `- ${s.name} image=${s.imageTag}${s.characterId ? ` char=${s.characterId}` : ""} exprs=[${ex}]\n`;
    }
  }

  body += `\n`;
  for (const ch of project.chapters) {
    body += `## ${ch.title}\n`;
    if (ch.synopsis) body += `${ch.synopsis}\n`;
    body += exportChapterPlain(ch.blocks, project.characters) + "\n";
  }

  if (body.length > maxChars) {
    return body.slice(body.length - maxChars);
  }
  return body;
}

function exportChapterPlain(
  blocks: ScriptBlock[],
  characters: Character[]
): string {
  const map = charLookup(characters);
  return blocks
    .map((b) => {
      switch (b.type) {
        case "label":
          return `[label ${b.name}]`;
        case "scene":
          return `[scene ${b.image}]`;
        case "show":
          return `[show ${b.image}]`;
        case "hide":
          return `[hide ${b.image}]`;
        case "narration":
          return `旁白: ${b.text}`;
        case "dialogue": {
          const name = map.get(b.characterId)?.displayName ?? b.characterId;
          return `${name}: ${b.text}`;
        }
        case "menu":
          return `选项: ${b.choices.map((c) => c.text).join(" / ")}`;
        case "jump":
          return `[jump ${b.target}]`;
        case "comment":
          return `# ${b.text}`;
        case "raw":
          return b.code;
        default:
          return "";
      }
    })
    .filter(Boolean)
    .join("\n");
}
