# 雨夜车站
# Generated by VN Script Studio
# Logline: 末班车延误的夜里，两个陌生人分享一把伞，却发现彼此寻找的是同一个人。

# Characters — generated by VN Script Studio

define linxia = Character("林夏", color="#7eb8da")
define zhouyu = Character("周屿", color="#c4a574")

# --- 末班广播 ---
# 雨夜月台，林夏等到延误通知，遇见周屿。
label start:
    scene bg station_night_rain with fade
    show linxia neutral at left
    "雨把站台洗成一条发亮的河。末班车的电子屏跳了两下，变成刺眼的「延误」。"
    linxia "……又是这样。"
    show zhouyu smile at right
    zhouyu "这把伞还能再挤一个人。如果你不介意潮湿的礼貌的话。"
    menu umbrella:
        "你要怎么做？"
        "接过伞沿":
            jump accept_umbrella
        "婉拒，继续等":
            jump refuse_umbrella
label accept_umbrella:
    linxia "谢谢。我在等一个人……也许她不会来了。"
    jump talk_rain
label refuse_umbrella:
    linxia "不用。雨停之前我还站得住。"
label talk_rain:
    zhouyu "那个人……也喜欢在这种天气失踪吗？"
