"""Ported from packages/core/src/renpy.ts"""
from __future__ import annotations

import json
import re
from typing import Dict, List, Optional

from app.domain.types import Character, ScriptBlock, VnProject


def _escape_renpy_string(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def _char_lookup(characters: List[Character]) -> Dict[str, Character]:
    lookup: Dict[str, Character] = {}
    for c in characters:
        lookup[c.id] = c
        lookup[c.defineName] = c
    return lookup


def _emit_block(
    block: ScriptBlock, chars: Dict[str, Character], indent: str = ""
) -> List[str]:
    lines: List[str] = []
    btype = block.get("type")
    if btype == "label":
        lines.append(f"{indent}label {block['name']}:")
    elif btype == "scene":
        transition = block.get("transition")
        lines.append(
            f"{indent}scene {block['image']}" + (f" with {transition}" if transition else "")
        )
    elif btype == "show":
        at = block.get("at")
        lines.append(f"{indent}show {block['image']}" + (f" at {at}" if at else ""))
    elif btype == "hide":
        lines.append(f"{indent}hide {block['image']}")
    elif btype == "narration":
        lines.append(f'{indent}"{_escape_renpy_string(block["text"])}"')
    elif btype == "dialogue":
        ch = chars.get(block.get("characterId"))
        who = ch.defineName if ch else "narrator"
        lines.append(f'{indent}{who} "{_escape_renpy_string(block["text"])}"')
    elif btype == "menu":
        menu_id = block.get("id")
        lines.append(f"{indent}menu" + (f" {menu_id}" if menu_id else "") + ":")
        prompt = block.get("prompt")
        if prompt:
            lines.append(f'{indent}    "{_escape_renpy_string(prompt)}"')
        for choice in block.get("choices", []) or []:
            lines.append(f'{indent}    "{_escape_renpy_string(choice["text"])}":')
            jump = choice.get("jump")
            child_blocks = choice.get("blocks")
            if jump:
                lines.append(f"{indent}        jump {jump}")
            elif child_blocks:
                for child in child_blocks:
                    lines.extend(_emit_block(child, chars, indent + "        "))
            else:
                lines.append(f"{indent}        pass")
    elif btype == "jump":
        lines.append(f"{indent}jump {block['target']}")
    elif btype == "return":
        lines.append(f"{indent}return")
    elif btype == "comment":
        lines.append(f"{indent}# {block['text']}")
    elif btype == "raw":
        for raw_line in block.get("code", "").split("\n"):
            lines.append(f"{indent}{raw_line}")
    return lines


def export_character_defines(project: VnProject) -> str:
    """Export character define lines for script.rpy header"""
    lines = ["# Characters — generated by VN Script Studio", ""]
    for c in project.characters:
        color = c.color or "#ffffff"
        lines.append(
            f'define {c.defineName} = Character("{_escape_renpy_string(c.displayName)}", color="{color}")'
        )
    return "\n".join(lines) + "\n"


def export_to_renpy(project: VnProject) -> str:
    """Export full project to a single .rpy string"""
    chars = _char_lookup(project.characters)
    parts: List[str] = [
        p
        for p in [
            f"# {project.title}",
            "# Generated by VN Script Studio",
            f"# Logline: {project.logline}" if project.logline else None,
            "",
            export_character_defines(project).rstrip("\n"),
            "",
        ]
        if p is not None
    ]

    for chapter in project.chapters:
        parts.append(f"# --- {chapter.title} ---")
        if chapter.synopsis:
            parts.append(f"# {chapter.synopsis}")
        in_label = False
        for block in chapter.blocks:
            if block.get("type") == "label":
                in_label = True
                parts.extend(_emit_block(block, chars, ""))
            else:
                parts.extend(_emit_block(block, chars, "    " if in_label else ""))
        parts.append("")

    return re.sub(r"\n{3,}", "\n\n", "\n".join(parts))


def _first_chapter_label(project: VnProject) -> Optional[str]:
    """First label name across chapters (entry point), if any."""
    for chapter in project.chapters:
        for block in chapter.blocks:
            if block.get("type") == "label":
                name = block.get("name")
                if name and name != "start":
                    return str(name)
    return None


def _slug_title(title: str) -> str:
    slug = re.sub(r"[^\w\u4e00-\u9fff]+", "_", (title or "vn").strip(), flags=re.UNICODE)
    slug = re.sub(r"^_+|_+$", "", slug)
    return slug[:48] or "vn"


def export_options_rpy(project: VnProject) -> str:
    """Minimal options.rpy — window name, resolution, save directory."""
    return f'''## options.rpy — generated by VN Script Studio

define config.name = _("{_escape_renpy_string(project.title or 'VN Script Studio')}")
define config.version = "0.1"
define gui.init(1280, 720)

define config.save_directory = "vnsstudio-{_slug_title(project.title)}"
define config.window_title = _("{_escape_renpy_string(project.title or 'VN Script Studio')}")
'''


def export_gui_rpy(project: VnProject) -> str:
    """Minimal generated gui.rpy — accent color from project or brand default."""
    accent = "#002fa7"
    for c in project.characters:
        if c.color:
            accent = c.color
            break
    return f'''## gui.rpy — minimal UI theme (generated by VN Script Studio)
## Swap in a full Ren'Py template gui.rpy for complete customization.

define gui.text_size = 22
define gui.name_text_size = 24
define gui.interface_text_size = 22
define gui.accent_color = "{accent}"
define gui.idle_color = "#888888"
define gui.hover_color = "{accent}"
define gui.selected_color = "{accent}"
define gui.insensitive_color = "#88888888"
'''


def export_script_rpy(project: VnProject) -> str:
    """script.rpy — story + a start label bridging to the first chapter."""
    body = export_to_renpy(project)
    first = _first_chapter_label(project)
    if first:
        body = (
            "label start:\n"
            f"    jump {first}\n\n"
            "# The actual story chapters follow below.\n\n"
            f"{body}"
        )
    else:
        body = "label start:\n    \"（空项目——请先在 VN Script Studio 中写开场。）\"\n\n" + body
    return body


def export_project_bundle(project: VnProject) -> Dict[str, str]:
    """Full Ren'Py project skeleton: script.rpy + options.rpy + gui.rpy + README.

    Drop the contents into a Ren'Py project's game/ folder to run.
    """
    return {
        "script.rpy": export_script_rpy(project),
        "options.rpy": export_options_rpy(project),
        "gui.rpy": export_gui_rpy(project),
        "README.txt": (
            "VN Script Studio — Ren'Py 项目骨架\n"
            "===================================\n\n"
            "把本目录（game/ 内的 4 个文件）复制到 Ren'Py 项目（或新建项目）的 "
            "game/ 目录，启动引擎即可运行。\n\n"
            "文件说明：\n"
            "- script.rpy  剧本（含 label start 入口）\n"
            "- options.rpy 窗口名 / 分辨率 / 存档目录\n"
            "- gui.rpy     极简 UI 主题（可换官方模板 gui.rpy）\n\n"
            "提示：\n"
            "- 角色立绘 / 背景图需自行放入 game/images 并保证文件名与 script 中一致。\n"
            "- 分支 menu 已保留；jump 目标为 label 名。\n"
            "- 由 VN Script Studio 生成；AI 内容请人工审稿后再发行。\n"
        ),
    }


def project_to_context(project: VnProject, max_chars: int = 12000) -> str:
    """Compact text dump for AI context (not full .rpy)"""
    chars_lines = []
    for c in project.characters:
        line = f"- {c.displayName} ({c.defineName})"
        if c.voice:
            line += f": {c.voice}"
        if c.bio:
            line += f" | {c.bio}"
        if c.relationships:
            line += f" | 关系: {c.relationships}"
        chars_lines.append(line)
        mind = (getattr(c, "voiceMind", None) or "").strip()
        if mind:
            snippet = mind if len(mind) <= 600 else mind[:588] + "…"
            chars_lines.append(f"  思维卡:\n{snippet}")
        corpus = getattr(c, "voiceCorpus", None) or []
        if corpus:
            from app.core.character_voice.corpus import format_corpus_for_prompt

            bit = format_corpus_for_prompt(c, max_samples=4, max_chars=700)
            if bit:
                chars_lines.append(bit)
    chars = "\n".join(chars_lines)

    bible = project.bible
    body = f"# Project: {project.title}\n"
    if project.logline:
        body += f"Logline: {project.logline}\n"
    if project.genre:
        body += f"Genre: {project.genre}\n"
    if (bible and bible.world) or project.lore:
        body += f"\n世界观:\n{(bible.world if bible else None) or project.lore}\n"
    if bible and bible.background:
        body += f"\n故事背景:\n{bible.background}\n"
    if bible and bible.outline:
        body += f"\n大纲:\n{bible.outline}\n"
    if bible and bible.themes:
        body += f"\n主题/基调:\n{bible.themes}\n"
    if bible and bible.notes:
        body += f"\n备忘:\n{bible.notes}\n"

    body += f"\nCharacters:\n{chars or '(无)'}\n"

    locs = project.locations or []
    if locs:
        body += "\nLocations:\n"
        for l in locs:
            body += f"- {l.name}" + (f" [{l.imageTag}]" if l.imageTag else "") + (
                f": {l.description}" if l.description else ""
            ) + "\n"

    links = project.locationLinks or []
    if links:
        by_id = {l.id: l.name for l in locs}
        body += "Location links:\n"
        for link in links:
            body += (
                f"- {by_id.get(link.fromId, link.fromId)} --{link.relation}--> "
                f"{by_id.get(link.toId, link.toId)}"
                + (f" ({link.note})" if link.note else "")
                + "\n"
            )

    variables = project.variables or []
    if variables:
        body += "\nVariables / 状态机:\n"
        for v in variables:
            body += (
                f"- {v.name} ({v.key}: {v.type}) = {json.dumps(v.value, ensure_ascii=False)}"
                + (f" [char:{v.bindCharacterId}]" if v.bindCharacterId else "")
                + (f" // {v.note}" if v.note else "")
                + "\n"
            )

    sprites = project.sprites or []
    if sprites:
        body += "\nSprites / 立绘:\n"
        for s in sprites:
            ex = ", ".join(e.tag for e in s.expressions)
            body += (
                f"- {s.name} image={s.imageTag}"
                + (f" char={s.characterId}" if s.characterId else "")
                + f" exprs=[{ex}]\n"
            )

    body += "\n"
    for ch in project.chapters:
        body += f"## {ch.title}\n"
        if ch.synopsis:
            body += f"{ch.synopsis}\n"
        body += _export_chapter_plain(ch.blocks, project.characters) + "\n"

    if len(body) > max_chars:
        return body[len(body) - max_chars :]
    return body


def _export_chapter_plain(blocks: List[ScriptBlock], characters: List[Character]) -> str:
    char_map = _char_lookup(characters)
    lines: List[str] = []
    for b in blocks:
        btype = b.get("type")
        if btype == "label":
            line: Optional[str] = f"[label {b['name']}]"
        elif btype == "scene":
            line = f"[scene {b['image']}]"
        elif btype == "show":
            line = f"[show {b['image']}]"
        elif btype == "hide":
            line = f"[hide {b['image']}]"
        elif btype == "narration":
            line = f"旁白: {b['text']}"
        elif btype == "dialogue":
            ch = char_map.get(b.get("characterId"))
            name = ch.displayName if ch else b.get("characterId")
            line = f"{name}: {b['text']}"
        elif btype == "menu":
            line = f"选项: {' / '.join(c['text'] for c in b.get('choices', []))}"
        elif btype == "jump":
            line = f"[jump {b['target']}]"
        elif btype == "comment":
            line = f"# {b['text']}"
        elif btype == "raw":
            line = b.get("code", "")
        else:
            line = ""
        if line:
            lines.append(line)
    return "\n".join(lines)
